### PR TITLE
Fixed actions in notifications

### LINKED ISSUE #1667: "Pending Shares" breaks Phoenix
... or is it just a "notification that requires an action" that breaks things?

**Steps to reproduce**
1. Have two users, `Alice` and `Bob`
2. Have the option `Automatically accept new incoming local user shares` in admin 'Sharing' settings set to `disabled` (aka "Pending Shares" enabled)
3. As `Alice` share a resource with `Bob`
4. Log in as `Bob`

**Expected behavior**
Bob can log in as usual, the file list and rest of the UI loads and he has an unread notification that tells him about the pending share and offers to accept or decline it.

**Actual behavior**
Loading freezes somewhere in between and the user can't do anything.

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Removed sort of actions, replaced buttons with oc-button component and added reload action for files list.

## Related Issue

- Refs #1186 
- Fixes #1667

## How Has This Been Tested?

- test environment: Manually
1. Turn off auto-accept of shares
2. Share file with another user
3. Open notifications drop
4. Decline notification
5. Accept notification

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

File: src/components/Notifications.vue [hunk 1]
```diff
@@ -27,24 +50,51 @@ import { mapGetters, mapActions } from 'vuex'
...
+    },
+    reloadFilesList (path) {
+      this.loadFolder({
+        client: this.$client,
+        absolutePath: path,
+        $gettext: this.$gettext,
+        routeName: this.$route.name
+      }).catch((error) => {
+        this.showMessage({
+          title: this.$gettext('Loading folder failed'),
```
Comment (DeepDiver1975) [inline src/components/Notifications.vue]: Please copy texts to make sure we have them consistent and reduce the amount of translations - THX

Comment (LukasHirt) [reply src/components/Notifications.vue]: Fixed

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUITrashbin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4567/10

<p>





</p></details>
