### PR TITLE
fix sidebar behavior on smaller screens

### LINKED ISSUE #672: File version and layout left overs
- [ ] checking multiple files confuses the sidebar
  1. select file with no version
  2. select file with version
screenshot from 2019-02-14 17-03-17

- [ ] sidebar layout a bit messed on smaller screens
screenshot from 2019-02-14 16-16-39

### PR DESCRIPTION
**Pull request by scramb**
## Description

Fix Sidebar behavior on smaller screens and sidebar confusion if multiple files selected as descriped in #672 

## Related Issue

- Fixes #672 

## How Has This Been Tested?

- test resolution: 1024x768 768x1024

## Screenshots: 
screenshot_2019-02-18 owncloud phoenix 1
screenshot_2019-02-18 owncloud phoenix

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Code changes

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
screenshot from 2019-02-19 08-59-02

I see two scroll bars on the right ... Chromium 72

**Comment by DeepDiver1975** [comment]
screenshot from 2019-02-19 09-03-03

File: src/components/OcAppSideBar.vue [hunk 1]
```diff
@@ -46,8 +46,10 @@ export default {
 </script>
 <style scoped>
 .sidebar-container {
+  max-height: calc(100vh - 115px);
```
Comment (tempelgogo) [inline src/components/OcAppSideBar.vue]: this one (hopefully) shouldn't glitch in IE
