### PR TITLE
Remove outline around files list

### LINKED ISSUE #3551: File list has border on click
When you click into the file list, the list has some kind of selection border in blue (see screenshot). Need to bisect when this was introduced. Probably with the permanently visible left sidebar.

### Steps to reproduce
1. Open phoenix.owncloud.com
2. Click on anything in the file list (whitespace, row, ...)
3. A blue border around the file list area appears

### Expected behaviour
No selection border appears.

### Actual behaviour
A selection border appears.

### Client configuration
**Browser:** Chrome for macOS (doesn't happen in Safari)

**Operating system:** macOS

### Screenshot
Screenshot 2020-05-29 at 12 26 20

### LINKED ISSUE #3747: do not add border to filelist when clicking it
### Steps to reproduce
1. click in the white area below the existing files

### Expected behaviour
nothing should visually change

### Actual behaviour
The file list gets a border.

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
The files list was displaying an outline when it received focus after a click.
Since the focus is meant only programmatically, the outline was not supposed to be displayed.

## Related Issue

- Fixes #3747
- Fixes #3551

## How Has This Been Tested?

Click on a row in files list or in the header whitespace.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

### CODE REVIEW

File: apps/files/src/components/FilesApp.vue [hunk 1]
```diff
@@ -171,3 +171,9 @@ export default {
   }
 }
 </script>
+
+<style scoped>
+.files-list-wrapper:focus {
```
Comment (LukasHirt) [inline apps/files/src/components/FilesApp.vue:176]: Since it is not an ODS component I am putting the styles in here on purpose.

**Comment by kulmann** [comment]
Oh, why did you tick `breaking change` in the PR description? 🤔

**Comment by LukasHirt** [comment]
> Oh, why did you tick breaking change in the PR description? 🤔

Damn, that's wrong 🤦 Thanks for spotting!
