### PR TITLE
Fix avatar spinner size

### LINKED ISSUE #2921: oc-avatar shifts layout after loading
### Steps

1. Create two users "user1" and "user2" without avatars
1. Login as "user1"
1. Open the collaborators panel for any resource
1. Add a new collaborator
1. Type "us" and observe closely the avatar in the autocomplete dropdown
1. Select "user2" and confirm
1. Open the collaborators panel again and observe closely the avatar in the collaborators list

### Expected result

- Only one spinner in place of the avatar while loading.
- After the avatar placeholder appears, the layout must stay in place

### Actual result

- **Two** spinners appear above each other in place of the avatar
- After the avatar placeholder appears, the layout is shifting slightly

Note that some random test failures exist in CI with the "iPhone" form factor as sometimes the avatar load timing is different and the container layout shifts before the test runner can click on a selected element.

### Version
Phoenix master e0df137a74cd6a0a28a0b5d328abc65127fab364

It is possible that the issue is related to the component in ODS, but is not confirmed yet as ODS doesn't provide an example of the spinner.

@kulmann as discussed.

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Refactored avatar component logic to be located only in Phoenix core.
Moved spinner into the avatar component.
Adjusted spinner size to match the one of the avatar to avoid layout shifting

## Related Issue
Fix #2921 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

File: apps/files/src/components/Collaborators/AutocompleteItem.vue [hunk 1]
```diff
@@ -1,12 +1,9 @@
 <template>
   <div class="uk-flex uk-flex-middle">
-    <oc-spinner v-if="loading" uk-spinner="ratio:1.6" class="uk-margin-small-right" :aria-label="$gettext('Loading avatar')" />
+    <avatar v-if="item.value.shareType === 0" class="uk-margin-small-right" :width="50" :userid="avatar" :userName="item.label" />
```
Comment (kulmann) [inline apps/files/src/components/Collaborators/AutocompleteItem.vue]: Use `shareTypes.user` from `helpers/shareTypes.js` here

File: apps/files/src/components/Collaborators/AutocompleteItem.vue [hunk 2]
```diff
@@ -1,12 +1,9 @@
...
     <template v-else>
-      <oc-avatar v-if="item.value.shareType === 0" :src="avatar" class="uk-margin-small-right" :width="50" :userName="item.label" />
-      <template v-else>
-        <oc-icon v-if="item.value.shareType === 1" class="uk-margin-small-right" name="group" size="large" />
-        <oc-icon v-else class="uk-margin-small-right" name="person" size="large" />
-      </template>
+      <oc-icon v-if="item.value.shareType === 1" class="uk-margin-small-right" name="group" size="large" />
```
Comment (kulmann) [inline apps/files/src/components/Collaborators/AutocompleteItem.vue]: `shareTypes.group`

File: apps/files/src/components/Collaborators/Collaborator.vue [hunk 3]
```diff
@@ -2,9 +2,8 @@
   <div>
     <div v-if="$_reshareInformation" class="uk-text-meta uk-flex uk-flex-middle uk-margin-small-bottom"><oc-icon name="repeat" class="uk-margin-small-right" /> {{ $_reshareInformation }}</div>
     <div class="files-collaborators-collaborator-information uk-flex uk-flex-wrap uk-flex-middle">
-      <oc-spinner v-if="loading" key="collaborator-avatar-spinner" uk-spinner="ratio:1.6" class="uk-margin-small-right" :aria-label="$gettext('Loading')"/>
-      <div v-else key="collaborator-avatar-loaded">
-        <oc-avatar v-if="collaborator.info.share_type === '0'" :src="avatar" class="uk-margin-small-right" :width="50" :userName="collaborator.displayName" />
+      <div key="collaborator-avatar-loaded">
+        <avatar v-if="collaborator.info.share_type === '0'" class="uk-margin-small-right" :width="50" :userid="collaborator.name" :userName="collaborator.displayName" />
         <div v-else key="collaborator-avatar-placeholder">
           <oc-icon v-if="collaborator.info.share_type === '1'" class="uk-margin-small-right" name="group" size="large" />
```
Comment (kulmann) [inline apps/files/src/components/Collaborators/Collaborator.vue]: `shareTypes.group`

File: apps/files/src/components/Collaborators/Collaborator.vue [hunk 4]
```diff
@@ -2,9 +2,8 @@
   <div>
     <div v-if="$_reshareInformation" class="uk-text-meta uk-flex uk-flex-middle uk-margin-small-bottom"><oc-icon name="repeat" class="uk-margin-small-right" /> {{ $_reshareInformation }}</div>
     <div class="files-collaborators-collaborator-information uk-flex uk-flex-wrap uk-flex-middle">
-      <oc-spinner v-if="loading" key="collaborator-avatar-spinner" uk-spinner="ratio:1.6" class="uk-margin-small-right" :aria-label="$gettext('Loading')"/>
-      <div v-else key="collaborator-avatar-loaded">
-        <oc-avatar v-if="collaborator.info.share_type === '0'" :src="avatar" class="uk-margin-small-right" :width="50" :userName="collaborator.displayName" />
+      <div key="collaborator-avatar-loaded">
+        <avatar v-if="collaborator.info.share_type === '0'" class="uk-margin-small-right" :width="50" :userid="collaborator.name" :userName="collaborator.displayName" />
```
Comment (kulmann) [inline apps/files/src/components/Collaborators/Collaborator.vue]: `shareTypes.user`

File: src/components/Avatar.vue [hunk 5]
```diff
@@ -35,22 +38,24 @@ export default {
...
+            throw new Error('Network response was not ok.')
+          })
+          .then(blob => {
+            this.loading = false
+            this.avatarSource = window.URL.createObjectURL(blob)
+          })
+          .catch(error => {
+            this.avatarSource = ''
+            this.loading = false
+            console.log('There has been a problem with your fetch operation: ', error.message)
```
Comment (kulmann) [inline src/components/Avatar.vue]: Let's change the log msg to `... with the image fetch operation` or something like that 😁

File: src/phoenix.js [hunk 6]
```diff
@@ -64,6 +66,7 @@ Vue.use(VueMeta, {
 
 Vue.component('drag', Drag)
 Vue.component('drop', Drop)
+Vue.component('avatar', Avatar)
```
Comment (kulmann) [inline src/phoenix.js]: Vue style guide suggests to use component names with at least two words / fragments, to avoid clashes with pure html tags (which are always single worded), also to support readability (`it's not single-word, so it can't be html` as someone who is new to phoenix). I suppose that would be a good idea here as well. 🤷‍♂

**Comment by kulmann** [comment]
The approach to have and use only one, globally available, avatar component is both good and useful. 🚀

File: src/components/Avatar.vue [hunk 7]
```diff
@@ -35,22 +38,24 @@ export default {
...
+          })
+      }, 5000)
```
Comment (PVince81) [inline src/components/Avatar.vue]: damn, I forgot to remove this :man_facepalming:

File: apps/files/src/components/Collaborators/AutocompleteItem.vue [hunk 8]
```diff
@@ -1,12 +1,9 @@
...
   <div class="uk-flex uk-flex-middle">
-    <oc-spinner v-if="loading" uk-spinner="ratio:1.6" class="uk-margin-small-right" :aria-label="$gettext('Loading avatar')" />
+    <avatar-image v-if="item.value.shareType === shareTypes.user" class="uk-margin-small-right" :width="50" :userid="item.value.shareWith" :userName="item.label" />
     <template v-else>
-      <oc-avatar v-if="item.value.shareType === 0" :src="avatar" class="uk-margin-small-right" :width="50" :userName="item.label" />
-      <template v-else>
-        <oc-icon v-if="item.value.shareType === 1" class="uk-margin-small-right" name="group" size="large" />
-        <oc-icon v-else class="uk-margin-small-right" name="person" size="large" />
-      </template>
+      <oc-icon v-if="item.value.shareType === shareTypes.group" class="uk-margin-small-right" name="group" size="large" />
```
Comment (LukasHirt) [inline apps/files/src/components/Collaborators/AutocompleteItem.vue]: Add key to v-if, v-else

File: apps/files/src/components/Collaborators/Collaborator.vue [hunk 9]
```diff
@@ -2,11 +2,10 @@
...
     <div v-if="$_reshareInformation" class="uk-text-meta uk-flex uk-flex-middle uk-margin-small-bottom"><oc-icon name="repeat" class="uk-margin-small-right" /> {{ $_reshareInformation }}</div>
     <div class="files-collaborators-collaborator-information uk-flex uk-flex-wrap uk-flex-middle">
-      <oc-spinner v-if="loading" key="collaborator-avatar-spinner" uk-spinner="ratio:1.6" class="uk-margin-small-right" :aria-label="$gettext('Loading')"/>
-      <div v-else key="collaborator-avatar-loaded">
-        <oc-avatar v-if="collaborator.info.share_type === '0'" :src="avatar" class="uk-margin-small-right" :width="50" :userName="collaborator.displayName" />
+      <div key="collaborator-avatar-loaded">
+        <avatar-image v-if="$_shareType === shareTypes.user" class="uk-margin-small-right" :width="50" :userid="collaborator.name" :userName="collaborator.displayName" />
         <div v-else key="collaborator-avatar-placeholder">
-          <oc-icon v-if="collaborator.info.share_type === '1'" class="uk-margin-small-right" name="group" size="large" />
+          <oc-icon v-if="$_shareType === shareTypes.group" class="uk-margin-small-right" name="group" size="large" />
```
Comment (LukasHirt) [inline apps/files/src/components/Collaborators/Collaborator.vue]: Add key to v-if, v-else

File: src/components/Avatar.vue [hunk 10]
```diff
@@ -1,12 +1,15 @@
 <template>
   <component :is="type" v-if="enabled">
-    <oc-avatar :width="width" :loading="loading" :src="avatarSource" :userName="userName" />
+    <oc-spinner v-if="loading" size="small" key="collaborator-avatar-spinner" :aria-label="$gettext('Loading')"
```
Comment (LukasHirt) [inline src/components/Avatar.vue]: Add key to v-if, v-else

**Comment by PVince81** [comment]
@LukasHirt I've added the requested keys, please recheck

**Comment by PVince81** [comment]
and I forgot the changelog entry as this is a bugfix
