### PR TITLE
Unblock unfinished sharing input

### LINKED ISSUE #1796: unfinished sharing locks up the sharing dialog
### Steps to reproduce
1. open the collaborators dialog
2. enter a user in the input field
3. click on the sharing button of an other resource

### Expected behaviour
the user should be able to add collaborators to the selected resource

### Actual behaviour
The input field is greyed-out, no collaborators can be added

out

### PR DESCRIPTION
**Pull request by Julian1998**
## Description

Resets the collaboration edit vuex state when mounted

## Related Issue

- Fixes #1796 

## Motivation and Context

Small bugfix

## How Has This Been Tested?

- checkout the description of #1796 
- it should be fixed xD

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

File: apps/files/src/components/Collaborators/NewCollaborator.vue [hunk 1]
```diff
@@ -190,6 +190,7 @@ export default {
   mounted () {
     // Ensure default role is not undefined
     this.selectedNewRole = this.defaultRole
+    this.toggleCollaboratorsEdit(false)
```
Comment (LukasHirt) [inline apps/files/src/components/Collaborators/NewCollaborator.vue]: Move it to the root component of the collaborators sidebar pls - `FileSharingSidebar.vue`

Comment (Julian1998) [reply apps/files/src/components/Collaborators/NewCollaborator.vue]: @LukasHirt Done!

Comment (LukasHirt) [reply apps/files/src/components/Collaborators/NewCollaborator.vue]: Thanks! 👍
