### PR TITLE
[tests-only] Fix waiting between upload & deletes

### LINKED ISSUE #4301: Intermittent fail of tests/acceptance/features/webUIFiles/versions.feature:14
I have seen this twice today in OCIS testing:
https://drone.owncloud.com/owncloud/ocis/1365/37/7
```
2) Scenario: upload new file with same name to see if different versions are shown (attempt 1, retried) # tests/acceptance/features/webUIFiles/versions.feature:14
   ✔ Before # tests/acceptance/setup.js:28
   ✔ Before # tests/acceptance/setup.js:32
   ✔ Before # tests/acceptance/setup.js:36
   ✔ Before # tests/acceptance/setup.js:46
   ✔ Before # tests/acceptance/setup.js:68
   ✔ Before # tests/acceptance/setup.js:75
   ✔ Before # tests/acceptance/stepDefinitions/filesContext.js:18
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:234
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:273
   ✔ Given these users have been created with default attributes: # tests/acceptance/stepDefinitions/provisioningContext.js:199
       | username |
       | user0    |
       | user1    |
   ✔ Given user "user0" has logged in using the webUI # tests/acceptance/stepDefinitions/loginContext.js:67
   ✔ And the user has browsed to the files page # tests/acceptance/stepDefinitions/filesContext.js:82
   ✔ And user "user0" has uploaded file with content "lorem content" to "lorem.txt" # tests/acceptance/stepDefinitions/filesContext.js:92
   ✔ And user "user0" has uploaded file with content "new lorem content" to "lorem.txt" # tests/acceptance/stepDefinitions/filesContext.js:92
   ✔ When the user browses to display the "versions" details of file "lorem.txt" # tests/acceptance/stepDefinitions/filesContext.js:112
   ✔ Then the content of file "lorem.txt" for user "user0" should be "new lorem content" # tests/acceptance/stepDefinitions/filesContext.js:482
   ✖ And the versions list should contain 2 entries # tests/acceptance/stepDefinitions/filesContext.js:458
       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

       2 !== 1

           + expected - actual

           -2
           +1

           at _callee20$ (/srv/app/phoenix/tests/acceptance/stepDefinitions/filesContext.js:460:17)
           at tryCatch (/srv/app/phoenix/node_modules/regenerator-runtime/runtime.js:63:40)
           at Generator.invoke [as _invoke] (/srv/app/phoenix/node_modules/regenerator-runtime/runtime.js:293:22)
           at Generator.next (/srv/app/phoenix/node_modules/regenerator-runtime/runtime.js:118:21)
           at asyncGeneratorStep (/srv/app/phoenix/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
           at _next (/srv/app/phoenix/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
           at processTicksAndRejections (internal/process/task_queues.js:86:5)
   ✔ After # tests/acceptance/stepDefinitions/provisioningContext.js:226
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:285
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:258
   ✔ After # tests/acceptance/setup.js:110
   ✔ After # tests/acceptance/setup.js:106
   ✔ After # tests/acceptance/setup.js:102
   ✔ After # tests/acceptance/setup.js:95
   ✔ After # tests/acceptance/setup.js:86
   ✔ After # tests/acceptance/setup.js:54
```

It usually passes. I am suspicious that there might be a timing problem - the 2 uploads are done using WebDav. The content of the file is the 2nd-uploaded content, so that is good. Maybe there is an issue with doing the uploads too close together. I know that in core test code we space these kinds of steps out 1 second apart to avoid known issues (features) about Unix timestamps that have only 1-second resolution.

Is there something that we should do in the test code to avoid known close-together-in-time version issues?

### PR DESCRIPTION
**Pull request by individual-it**
## Description
the waiting before an upload or delete had an issue
the code waited before the upload in https://github.com/owncloud/phoenix/blob/034efba13d429b26b2cad7562d928866dfc84fe8/tests/acceptance/stepDefinitions/filesContext.js#L97
and after the waiting `timeOfLastUploadOperation` is set but the upload hasn't even started, so if the upload is slow the waiting will be too short in the next upload

this PR f makes sure the time variable is only set after the upload or delete

besides that there have been two functions uploading files with content, I've deleted one of them

## Related Issue

- Fixes #4301

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
🚀

File: tests/acceptance/helpers/webdavHelper.js [hunk 1]
```diff
@@ -34,11 +37,25 @@ exports.download = function(userId, file) {
...
+
+  /**
+   * makes sure delete operations are carried out maximum once a second to avoid trashbin issues
+   * see https://github.com/owncloud/core/issues/23151
+   */
+  const timeSinceLastDelete = Date.now() - timeOfLastDeleteOperation
+  if (timeSinceLastDelete < 1001) {
+    await client.pause(1001 - timeSinceLastDelete)
+  }
+  timeOfLastDeleteOperation = Date.now()
```
Comment (phil-davis) [inline tests/acceptance/helpers/webdavHelper.js:51]: I guess this is not essential to do here, because `timeOfLastDeleteOperation` will be set after `.delete(davPath, userId)` happens. But it does not hurt.

**Review by phil-davis — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

File: tests/acceptance/helpers/webdavHelper.js (hunk 1 above)
Comment (individual-it) [reply tests/acceptance/helpers/webdavHelper.js]: I've deleted that extra line

**Review by dpakach — APPROVED** [review]
