### PR TITLE
close #665 fix file filters

### LINKED ISSUE #665: Local File Filter dysfunctional
Local File Filter broken since https://github.com/owncloud/phoenix/pull/623 due to component splitting.

## Related Issue:
- #662 local folder search broken

## Description:
prepared in #666

## ToDo:
- [ ] use event's instead of v-model & inject value into vuetify `input-value`
- [ ] test all filters

### PR DESCRIPTION
**Pull request by tempelgogo**
## Description
moved filter into `fileFilters.js`, load in store.
Split v-model from checkbox to catch event manually & inject value into v-checkbox `input-value` prop

## Related Issue

- Fixes #665

## Motivation and Context
filters were hardcoded before, but we need them at a few places...
abstract them in state.

## How Has This Been Tested?

- create folder, directory & hidden files
- check & uncheck file filters

## Screenshots (if appropriate):
design has not changed, It's just working again

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Code changes

### CODE REVIEW

File: apps/files/src/fileFilters.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+export const fileFilters = [{
+  name: 'Files',
```
Comment (DeepDiver1975) [inline apps/files/src/fileFilters.js]: still no translation :see_no_evil: ;-)

Comment (tempelgogo) [reply apps/files/src/fileFilters.js]: `vue-gettext` has no global available getter AFAIK; so i needed to wrap it into a real SingleFileComponent, thus get the ViewModel access via `this`
I don't want to pollute the TopBar, so I've created a new File.

If you like it, i could squash it.
