### PR TITLE
Fixed existing collaborators in autocomplete

### LINKED ISSUE #2419: creating share with user and group having same name is not possible
### Steps to reproduce
1. Cretate two users ```user1``` and ```user2```. And create a group ```user1```
2. Add ```user2``` to group ```user1``` and share some file ```abc.txt``` with group ```user1```
3. Now try to share the same file ```abc.txt``` with user ```user1```. Here ```user1``` is not displayed in the sharing autocomplete list.
### Expected behaviour
It must be possible to share file with user and group having same name
### Actual behaviour
Sharing with user and group with same name is not possible

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Do not hide collaborator if another entry with the same name exists if they are not the same type.

## Related Issue

- Fixes #2419

## How Has This Been Tested?

- test environment: Acceptance tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

File: apps/files/src/components/Collaborators/NewCollaborator.vue [hunk 1]
```diff
@@ -169,7 +169,10 @@ export default {
             )
 
             const exists = this.shares.find(existingCollaborator => {
-              return collaborator.value.shareWith === existingCollaborator.name
+              return (
+                collaborator.value.shareWith === existingCollaborator.name &&
+                parseInt(collaborator.value.shareType) === parseInt(existingCollaborator.info.share_type)
```
Comment (PVince81) [inline apps/files/src/components/Collaborators/NewCollaborator.vue]: in general always use `parseInt(x, 10)` to be on the safe side

Comment (LukasHirt) [reply apps/files/src/components/Collaborators/NewCollaborator.vue]: Right - fixed
