### PR TITLE
Block more then one click

### LINKED ISSUE #1537: Multiple files delete confirmation - can be confirmed multiple times
### Steps to reproduce
1. select multiple files
2. delete them all
3. click OK on the confirmation dialog
4. see deletions happening
5. click OK again
6. all deletions will be triggered again

### Expected behaviour
- button shall be grayed out
- or what ever

### Actual behaviour
- the user can click the button over and over again

### PR DESCRIPTION
**Pull request by Julian1998**
## Description
Added boolean hepler to detect clicks

## Related Issue

- Fixes #1537 

## How Has This Been Tested?

- try to force the confirm button to send an other delete request when in the dialog prompt

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

File: apps/files/src/components/ocDialogPrompt.vue [hunk 1]
```diff
@@ -17,7 +17,7 @@
     </template>
     <template slot="footer">
         <oc-button :id="ocCancelId" :disabled="ocLoading" @click.stop="onCancel">{{ _ocCancelText }}</oc-button>
-        <oc-button :disabled="ocLoading || ocError !== null || inputValue === '' || clicked"
```
Comment (DeepDiver1975) [inline apps/files/src/components/ocDialogPrompt.vue]: remove all remaining occurances of clicked?

File: apps/files/src/components/ocDialogPrompt.vue [hunk 2]
```diff
@@ -47,6 +47,7 @@ export default {
     ocLoading: { type: Boolean, default: false },
     ocCancelId: String,
     ocConfirmId: String,
+    ocConfirmed: { type: Boolean, default: false },
```
Comment (DeepDiver1975) [inline apps/files/src/components/ocDialogPrompt.vue]: instead of this you can reset clicked to false within the watcher for ocActive - https://github.com/owncloud/phoenix/blob/34f06ae308c25cd6df19307101d32f0a2837bb9c/apps/files/src/components/ocDialogPrompt.vue#L71

Comment (Julian1998) [reply apps/files/src/components/ocDialogPrompt.vue]: that's right. Why the hell did I mess around with promises and callbacks

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUITrashbin</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4626/

<p>
















</p></details>
