### PR TITLE
Hide versions tab for folders

### LINKED ISSUE #1751: a file with versions makes a version entry to be shown for the parent folder
### Steps to reproduce
1. upload a file to a folder
2. upload the same file again and overwrite it, to generate at lease one version entry
3. open the versions tab of the parent folder

### Expected behaviour
versions tab should not be there or at lease empty, folders cannot have versions

### Actual behaviour
version tab shows a version, restore and download buttons are displayed but clicking them has no visible effect

image

### PR DESCRIPTION
**Pull request by LukasHirt**
## Related Issue

- Fixes #1751

## How Has This Been Tested?

- test environment: Manually
1. Click on file row
2. Click on folder row

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4623/

<p>







</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4623/

<p>















</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4623/

<p>




















</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4623/

<p>



















































</p></details>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong></strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/phoenix/4623/

<p>



















































</p></details>

File: apps/files/src/default.js [hunk 1]
```diff
@@ -20,8 +20,8 @@ const appInfo = {
     {
       app: 'files-version',
       component: FileInfoVersions,
-      enabled (capabilities) {
-        return !!capabilities.core
+      enabled (capabilities, highlightedFile) {
```
Comment (DeepDiver1975) [inline apps/files/src/default.js]: for the future - we might want to do this with an object {capabilties, highlightedFile} - I think this will be extended in the future ...
