### PR TITLE
Fixed topbar and named routes

### LINKED ISSUE #590: FileactionsTab seems broken
### Steps to reproduce
1. Open MarkDown file
2. Click 'Markdown Editor'

### Expected behaviour
markdown editor opens
Tell us what should happen

### Actual behaviour
pdf editor opens

### To Do
discuss active File Parameter....
1. Is the open file visible in URI & we force all app's to receive filePath in URI ?
2. Or do we keep the current behaviour & store it in the vuex.

### PR DESCRIPTION
**Pull request by scramb**
## Description
* New Topbar component. 
* Less vuetify. 
* Apps got their own topbars
* named routes
    * appContent
    * appTopbar
    * fullscreen
* fixed markdown-editor open bug

## Related Issue
- Fixes #590
- Refs #576
- Refs #577
- Refs #579

## How Has This Been Tested?
- :hand: 

### New Topbar
screenshot_2019-02-06 owncloud phoenix
### Sidebar adjusted to topbar height
screenshot_2019-02-06 owncloud phoenix 1
### MarkdownEditorTopbar
screenshot_2019-02-06 owncloud phoenix 2
### Sticky fixed AppTopbar
screenshot_2019-02-06 owncloud phoenix 3

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt

## Checklist:

- [x] Code changes

## Open tasks:

- [ ] onSidebarOpen: scroll to the top ( maybe? )
- [x] fix create File/Folder
- [x] fix save button markdown-editor
- [x] fix pdf-viewer page count

### CODE REVIEW

File: src/components/Top-Bar.vue [hunk 1]
```diff
@@ -67,6 +61,45 @@ export default {
 }
 </script>
 
-<style scoped="true">
+<style scoped lang="scss">
```
Comment (DeepDiver1975) [inline src/components/Top-Bar.vue]: We dropped scss. do we need it again?

**Comment by DeepDiver1975** [comment]
I like the way it looks (by looking at the screenshots for now) ... but I think I missed the way this is implemented.

My idea was (as per #433 ) that a developer can use components to layout the app. The components shall handle all css magic - no css in the apps.

Maybe I missed one part in our conversation yesterday :man_shrugging: 

Pseudo app template:

```html
<template>
  <oc-app-content><!-- the screen space under the top bar -->
    <oc-app-toolbar><!-- second tool bar -->
      <v-icon/>
      <v-breadcrumb/>
      <!-- .... -->
    </oc-app-toolbar>
    <oc-app-sidebar left/>
    <oc-app-sidebar right/>
    <oc-app-footer/>
    <oc-app-main-content>
      <v-list>....</v-list>
    </oc-app-main-content>
  </oc-app-content>
</template>

File: src/components/Top-Bar.vue (hunk 1 above)
Comment (DeepDiver1975) [reply src/components/Top-Bar.vue]: this is because the docker build is failing I guess (havn't had a look yet)

File: apps/files/src/components/FilesTopBar.vue [hunk 2]
```diff
@@ -0,0 +1,322 @@
+<template>
+  <div class="grid-container">
```
Comment (DeepDiver1975) [inline apps/files/src/components/FilesTopBar.vue]: this is where I'd expect 
````html 
<oc-app-toolbar/>

File: apps/files/src/components/FilesTopBar.vue [hunk 3]
```diff
@@ -0,0 +1,322 @@
...
+        this.breadcrumbs.push(breadcrumb)
+        breadcrumb = {}
+      }
+      return this.breadcrumbs
+    }
+  }
+}
+</script>
+<style scoped>
+  .grid-container {
```
Comment (DeepDiver1975) [inline apps/files/src/components/FilesTopBar.vue]: hide in implementation of oc-app-toolbar

File: src/components/Top-Bar.vue (hunk 1 above)
Comment (scramb) [reply src/components/Top-Bar.vue]: Of course, we could also get rid of make completely and use an npm-baseimage for the pipeline. This would allow us to use sass/scss again, given that we are starting to develop our own base components.

File: apps/files/src/default.js [hunk 4]
```diff
@@ -31,11 +32,18 @@ const navItems = [{
 
 const routes = [{
   path: '',
-  redirect: `/${appInfo.id}/list/home`
+  redirect: `/${appInfo.id}/list/home`,
+  components: {
```
Comment (DeepDiver1975) [inline apps/files/src/default.js]: why are here two components - I don't get this ....

Comment (tempelgogo) [reply apps/files/src/default.js]: it's like a global vue-router managed slot.

Comment (DeepDiver1975) [reply apps/files/src/default.js]: so the route controls the views and their content .... processing ..... :robot: 

THX
